## Numpy assignment

 ### Question 1

#### Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [142]:
import numpy as np

In [143]:
def Vandermonde_matrix(vecotor, column_dimension=0, increment=False):
    row, = np.array(vecotor).shape # Getting the no of elements in the vector provided 
    array_1 = np.array(vecotor).reshape(row,1) # Reshaping the list to numpy array of shape row x 1
    matrix = array_1 ** 0 # making the a column array of 1
    for i in range( 1, column_dimension):
        if increment: # Depending on the boolean operator whether true or false the order of columns are determined
            matrix = np.append(matrix, (array_1**i), axis = 1)
        else:
            matrix = np.append((array_1**i), matrix,  axis = 1)
    return(matrix)   # returing the resulting vector        

In [159]:
vector = [1, 2, 3, 5]
print(Vandermonde_matrix(vector,4,True))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


### Ansewer using Numpy built in function numpy.vander

In [ ]:
vector = [1,2,3]

In [147]:
np.vander(vector,4,True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

 ### Question 2

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
   - i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

   - Input 10 20 30 40 50 60 70 80 90 100
   - y1 25 = (10+20+30+40)/4
   - y2 35 = (20+30+40+50)/4
   - y3 45 = (30+40+50+60)/4
   - y4 55 = (40+50+60+70)/4
   - y5 65 = (50+60+70+80)/4
   - y6 75 = (60+70+80+90)/4
   - y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [177]:
def movingAvg(dataSet, window):
    np_array = np.array(dataSet) 
    row, = np_array.shape
    movingAVGMatrix = np.array([])
    for i in range (0,row):
        temp_sum = (np_array[0+i:window+i]).sum()
        movingAVGMatrix = np.append(movingAVGMatrix,temp_sum)
        if window+i == row :
            break
    return movingAVGMatrix
    

In [192]:
movingAvg( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] ,3)

array([ 15.,  14.,  17.,  20.,  29.,  86., 148., 218., 252., 280., 349.])

### Solution 2

In [188]:
def movingAvg_2(dataSet, window = 2):
    moving_avg = np.cumsum(dataSet)
    moving_avg[window:] = moving_avg[window:] - moving_avg[:-window]
    return moving_avg[window-1:]    

In [193]:
print(movingAvg_2( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] ,3))

[ 15  14  17  20  29  86 148 218 252 280 349]
